#!/bin/bash

: '
 Dönüş Kodları
  0 : Başarılı
  1 : Verilen dosya yok 
  2 : Hatalı sayıda arguman girişi 
  3 : Girilen sınıf sayısı geçerli değil 
  4 : Girilen cinsiyet bilgisi geçerli değil
  5 : Dosyada isimler benzersiz değil
'

die() {
  >&2 echo $1
  exit $2
}

is_file_unique() {
  if ! ([[ $(cut -d "," -f 1 $1 | uniq -d) == "" ]] &&
        [[ $(cut -d "," -f 2 $1 | uniq -d) == "" ]]);then
    return 1
  fi
}

list_students() {
  IFS="," # IFS = Internal Field Seperator
  while read name surname gender c_no;do
    if [[ $2 =~ ^[0-9]+$ ]];then # Arguman bir tamsayı ise
      [[ $c_no -eq $2 ]] && echo $name $surname $gender
    elif [[ $2 =~ ^[eEkK]$ ]];then # Arguman e,E,k,K den biri ise
      [[ $(grep -ixE $gender <<< $2) ]] && echo $name $surname $c_no
    else
      echo $c_no $name $surname $gender
    fi
  done < $1
  return 0
}

arg_control() {
  [[ $# -gt 1 ]] && die "HATA: (0..1) arguman bekleniyordu, $# arguman girildi.!" 2
  if [[ $# -eq 1 ]];then # Arguman sayısı 1 ise
    [[ $1 =~ ^[eEkK]$ ]] || [[ $1 =~ [1-4] ]] && return 0
    [[ $1 =~ ^[0-9]+$ ]] && [[ $1 -lt 1 ]] || [[ $1 -gt 4 ]] && die "Girilen sınıf 1-4 aralığında değil!" 3
    die "HATA: Cinsiyet belirtmek için e, E, k, K karakterlerinden birini kullanın" 4
  fi
}

main() {
  [[ ! -f okul.csv ]] && die "HATA: okul.csv dosyası yok!" 1

  is_file_unique okul.csv; return_val=$?
  [[ ! $return_val -eq 0 ]] && 
  die "HATA: Dosya içeriği benzersiz elemanlardan oluşmuyor!" $return_val

  arg_control $@; return_val=$?
  [[ ! $return_val -eq 0 ]] && exit $return_val

  list_students okul.csv $@

}

main $@