#!/bin/bash

: '
 Dönüş Kodları
  0 : Başarılı
  1 : Hatalı sayıda arguman girişi
  2 : Girilen sınıf sayısı geçerli değil
  3 : Girilen cinsiyet bilgisi geçerli değil
'

write2stderr () {
  >&2 echo $@
}

arguman_kontrol () {
  if [[ $# -gt 1 ]] # $# Fonksiyonun arguman sayısı (betiğin değil)
  then
    >&2 echo "HATA: (0..1) arguman bekleniyordu, $# arguman girildi.!"
    return 1
  elif [[ $# -eq 1 ]] # Arguman sayısı 1 ise
  then
    if [[ $1 =~ ^[0-9]+$ ]] # Arguman bir tamsayı ise
    then
      if [[ $1 -gt 0 ]] && [[ $1 -lt 5 ]] # Argumanın değeri 0-4 aralığında ise
      then
        return 0
      else
        write2stderr "Girilen sınıf 1-4 aralığında değil!"
        return 2 
      fi
    elif [[ $1 =~ ^[eEkK]$ ]] # Arguman e,E,k,K den biri ise
    then
      return 0
    else 
      write2stderr "Cinsiyet belirtmek için e, E, k, K karakterlerinden birini kullanın"
      return 3
    fi
  else
    return 0
  fi
}


read_file () {
  if [[ -e $1 ]]
  then
    IFS=","
    while read name surname gender class
    do
      echo Name: $name , Surname: $surname, Gender: $gender, Class: $class
    done < $1
    return 0
  else
    write2stderr "Dosya yok!"
    return 1
  fi
}

main() {
  arguman_kontrol $@
  return_val=$?
  if [[ $return_val -eq 0 ]] # arguaman kontrol fonksiyonunun return değeri 0 ise
  then
    if [[ -e okul.csv ]]
    then
      echo "Dosya okunuyor..."
      read_file okul.csv $@
    else
      return 5
    fi
  else
    return $return_val
  fi
}

main $@
