#!/bin/bash

: '
 Dönüş Kodları
  0 : Başarılı
  1 : Verilen dosya yok 
  2 : Hatalı sayıda arguman girişi 
  3 : Girilen sınıf sayısı geçerli değil 
  4 : Girilen cinsiyet bilgisi geçerli değil
  5 : Dosyada isimler benzersiz değil
'

write2stderr() {
  >&2 echo $@
}

is_file_unique() {
  if ! ([[ $(cut -d "," -f 1 $1 | uniq -d) == "" ]] &&
        [[ $(cut -d "," -f 2 $1 | uniq -d) == "" ]]);then
    return 1
  fi
}

list_students() {
  IFS="," # IFS = Internal Field Seperator
  while read name surname gender c_no;do
    if [[ $2 =~ ^[0-9]+$ ]];then # Arguman bir tamsayı ise
      if [[ $c_no -eq $2 ]];then
        echo $name $surname $gender
      fi
    elif [[ $2 =~ ^[eEkK]$ ]];then # Arguman e,E,k,K den biri ise
      if [[ $(grep -ixE $gender <<< $2) ]];then
        echo $name $surname $c_no
      fi
    else
      echo $c_no $name $surname $gender
    fi
  done < $1
  return 0
}

arg_control() {
  if [[ $# -gt 1 ]];then # $# Fonksiyonun arguman sayısı (betiğin değil)
    >&2 echo "HATA: (0..1) arguman bekleniyordu, $# arguman girildi.!"
    return 2
  fi

  if [[ $# -eq 1 ]];then # Arguman sayısı 1 ise
    if [[ $1 =~ ^[0-9]+$ ]];then # Arguman bir tamsayı ise
      if [[ $1 -lt 1 ]] || [[ $1 -gt 4 ]];then # Arguman 0-4 aralığında ise
        write2stderr "Girilen sınıf 1-4 aralığında değil!"
        return 3
      fi
    elif [[ $1 =~ ^[eEkK]$ ]];then # Arguman e,E,k,K den biri ise
      return 0
    else 
      write2stderr "HATA: Cinsiyet belirtmek için 
                    e, E, k, K karakterlerinden birini kullanın"
      return 4
    fi
  fi
}

main() {
  if [[ ! -f okul.csv ]];then # Dosya yoksa
    write2stderr "HATA: okul.csv dosyası yok!"
    return 1
  fi

  is_file_unique okul.csv; return_val=$?
  if [[ ! $return_val -eq 0 ]];then # Dosya içeriği benzersiz değilse
    write2stderr "HATA: Dosya içeriği benzersiz elemanlardan oluşmuyor!"
    exit $return_val
  fi

  arg_control $@; return_val=$?
  if [[ ! $return_val -eq 0 ]];then # Argumanlar geçerli değilse
    exit $return_val
  fi

  list_students okul.csv $@

}

main $@